In [1]:
!pip install pandas

You should consider upgrading via the 'c:\python39\python.exe -m pip install --upgrade pip' command.


In [4]:
import pandas as pd 
df = pd.read_csv("reklamvesatis.csv")
df = df.iloc[:,1:len(df)]
df.head()

TV  radio  gazete  satislar
0  230.1   37.8    69.2      22.1
1   44.5   39.3    45.1      10.4
2   17.2   45.9    69.3       9.3
3  151.5   41.3    58.5      18.5
4  180.8   10.8    58.4      12.9

In [5]:
len(df)

200

In [6]:
# Tahmin için kullanılacak veri (X) ile, tahmini yapılacak olan verinin (y) ayrıştırılması
X = df.drop('satislar', axis=1)
y = df["satislar"]

In [7]:
X.head()

TV  radio  gazete
0  230.1   37.8    69.2
1   44.5   39.3    45.1
2   17.2   45.9    69.3
3  151.5   41.3    58.5
4  180.8   10.8    58.4

In [8]:
y.head()

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: satislar, dtype: float64

In [9]:
# pandas dataframe haline getirme
y = df[["satislar"]]

In [10]:
y.head()

satislar
0      22.1
1      10.4
2       9.3
3      18.5
4      12.9

In [11]:
!pip install sklearn

You should consider upgrading via the 'c:\python39\python.exe -m pip install --upgrade pip' command.


In [12]:
from sklearn.model_selection import train_test_split

In [13]:
# random_state değeri 1 olarak ayarlanırsa, eğitim ve test için ayrılan veriler sürekli değişir
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 1)

In [14]:
# Çoklu doğrusal tahmin
from sklearn.linear_model import LinearRegression
lm = LinearRegression()

In [15]:
type(lm)

sklearn.linear_model._base.LinearRegression

In [16]:
model = lm.fit(X_train, y_train)

In [17]:
yeni_veri = [[30],[10],[40]]
yeni_veri

[[30], [10], [40]]

In [18]:
yeni_veri = pd.DataFrame(yeni_veri).T
yeni_veri

0   1   2
0  30  10  40

In [19]:
model.predict(yeni_veri)

array([[6.18181031]])

In [20]:
y.head(10)

satislar
0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
5       7.2
6      11.8
7      13.2
8       4.8
9      10.6

In [22]:
X.head()

TV  radio  gazete
0  230.1   37.8    69.2
1   44.5   39.3    45.1
2   17.2   45.9    69.3
3  151.5   41.3    58.5
4  180.8   10.8    58.4

In [21]:
model.predict(X)[0:10]

array([[20.54159137],
       [12.35990106],
       [12.37795961],
       [17.6155085 ],
       [13.20848464],
       [12.56006616],
       [11.71188738],
       [12.07183086],
       [ 3.69181916],
       [12.501818  ]])

In [23]:
from sklearn.model_selection import cross_val_score

In [24]:
egitim_hatası = cross_val_score(model, X_train, y_train, cv=10, scoring="neg_mean_squared_error")
egitim_hatası

array([-2.1019073 , -2.48953197, -3.09704214, -2.34694216, -3.68175761,
       -1.8691401 , -3.18173007, -4.1927349 , -2.17128376, -8.03821974])

In [26]:
!pip install numpy

You should consider upgrading via the 'c:\python39\python.exe -m pip install --upgrade pip' command.


In [28]:
import numpy as np
egitim_hata_ort = np.mean(-egitim_hatası)
egitim_hata_ort

3.3170289742341255

In [29]:
# Test veri seti için
test_egitim_hatasi = cross_val_score(model, X_test, y_test, cv=10, scoring="neg_mean_squared_error")
test_egitim_hatasi

array([-4.38984219, -3.0979069 , -5.01750896, -2.96824449, -3.03201552,
       -1.69816908, -0.49509029, -1.23755559, -0.14213351, -2.87887471])

In [30]:
test_egitim_hatasi_ort = np.mean(-test_egitim_hatasi)
test_egitim_hatasi_ort

2.495734122608571

In [31]:
egitim_hata_ort_karakok = np.sqrt(egitim_hata_ort)
egitim_hata_ort_karakok

1.8212712522395245